Repository kyma-project/nats-manager, pull requests merged in 2023-10, with the labels that each got.

#162 Updated make module-build to use config file
  .gitignore
  Makefile
  hack/ci/Makefile
  module-config-template.yaml
  scripts/release.sh
Labels: size/M, lgtm

#161 add targets to update crd documentation
  Makefile
  docs/user/02-configuration.md
Labels: size/M, area/eventing, lgtm

#165 add info about NATS backend
  docs/user/README.md
Labels: lgtm, size/XS

#171 Release 1.0.1 version
  .version
  sec-scanners-config.yaml
Labels: lgtm, size/XS

#166 docs: Optimize module docs for website
  docs/user/_sidebar.md
Labels: documentation, area/documentation, lgtm, size/XS

#176 add missing reference to priorityClass
  config/manager/manager.yaml
Labels: area/eventing, lgtm, size/XS

#174 Implement nats CR with error state function
  testutils/options.go
Labels: lgtm, size/XS

#178 Increase memory limit for NATS manager deployment
  config/manager/manager.yaml
Labels: lgtm, size/XS

#179 Update version and image for release
  .version
  sec-scanners-config.yaml
Labels: lgtm, size/XS

#195 Bump dependencies
  cmd/main.go
  go.mod
  go.sum
  pkg/k8s/client.go
  testutils/integration/integration.go
Labels: size/M, lgtm

#197 Bump the golang image in the Dockerfile
  Dockerfile
Labels: lgtm, size/XS

#199 Bump sec-scanner-config.
  sec-scanners-config.yaml
Labels: lgtm, size/XS

#206 Update readme to include steps to install latest NATS manager and CR
  README.md
Labels: documentation, area/eventing, size/S, lgtm

#209 move doc to NATS repo
  docs/user/10-nats-server-system-events.md
  docs/user/_sidebar.md
Labels: size/M, lgtm
