Repository kyma-project/nats-manager, pull requests merged in 2023-07, with the labels that each got.

#73 Delete All NATS Resources
  .gitignore
  README.md
  api/v1alpha1/nats_status.go
  api/v1alpha1/nats_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/rbac/role.yaml
  go.mod
  go.sum
  internal/controller/nats/controller.go
  internal/controller/nats/deprovisioner.go
  internal/controller/nats/deprovisioner_test.go
  internal/controller/nats/integrationtests/controller/integration_test.go
  internal/controller/nats/mocks/client.go
  internal/controller/nats/mocks/js.go
  internal/controller/nats/mocks/natsconn.go
  internal/controller/nats/status.go
  pkg/k8s/client.go
  pkg/k8s/client_test.go
  pkg/k8s/mocks/client.go
  pkg/nats/client.go
  pkg/nats/client_unit_test.go
  pkg/nats/mocks/client.go
  testutils/integration/integration.go
  testutils/utils.go
Labels: size/XXL, area/eventing, lgtm

#80 Returning error in syncNATSStatusWithErr so reconciliation is triggered
  internal/controller/nats/provisioner_test.go
  internal/controller/nats/status.go
  internal/controller/nats/status_test.go
Labels: size/S, lgtm

#69 add e2e tests and run them as gh action
  .github/workflows/e2e.yml
  Makefile
  README.md
  e2e/cleanup/cleanup_test.go
  e2e/common/fixtures/fixtures.go
  e2e/common/k8s.go
  e2e/common/logger.go
  e2e/common/retry.go
  e2e/natsserver/natsserver_test.go
  e2e/scripts/natsbench.sh
  e2e/scripts/natsserver.sh
  e2e/setup/setup_test.go
  go.mod
  go.sum
  internal/controller/nats/mocks/controller.go
  internal/controller/nats/mocks/manager.go
  pkg/k8s/chart/mocks/renderer.go
  pkg/k8s/mocks/client.go
  pkg/manager/mocks/manager.go
  pkg/nats/mocks/client.go
Labels: size/XXL, area/ci, lgtm

#78 Added targets in Makefile to build OCI image and updated kustomize templates
  .env
  .github/workflows/e2e.yml
  Makefile
  config/default/kustomization.yaml
  config/manager/manager.yaml
  config/samples/default.yaml
  hack/ci/Makefile
  hack/get_kyma_file_name.sh
Labels: area/ci, size/L, lgtm

#82 Copy module template to job artifacts
  hack/ci/Makefile
Labels: lgtm, size/XS

#81 Added pre-main e2e jobs with lifecycle-manager
  .github/workflows/e2e.yml
  .github/workflows/pull-with-lifecycle-manager.yaml
  .gitignore
  Makefile
  hack/ci/Makefile
  hack/get_module_template_from_build_job.sh
Labels: area/ci, size/L, lgtm

#83 Added post-main e2e with lifecycle manager job
  .github/workflows/push-with-lifecycle-manager.yaml
  hack/get_module_template_from_build_job.sh
Labels: area/ci, size/L, lgtm

#86 Added e2e upgrade from fast-channel to current commit test jobs
  .github/workflows/pull-with-lifecycle-manager.yaml
  .github/workflows/push-with-lifecycle-manager.yaml
  Makefile
  api/v1alpha1/zz_generated.deepcopy.go
  e2e/common/fixtures/fixtures.go
  e2e/scripts/natsserver.sh
  e2e/setup/setup_test.go
  hack/ci/Makefile
  hack/verify_kyma_status.sh
Labels: area/ci, size/L, lgtm

#89 Fix post main e2e upgrade job
  .github/workflows/push-with-lifecycle-manager.yaml
Labels: area/ci, lgtm, size/XS

#87 review README
  README.md
Labels: documentation, area/documentation, area/eventing, size/L, lgtm
