Repository kyma-project/nats-manager, pull requests merged in 2023-09, with the labels that each got.

#129 Update deps
  .github/workflows/codequality.yml
  Dockerfile
  go.mod
  go.sum
  sec-scanners-config.yaml
Labels: area/eventing, lgtm

#128 Fix checkmarx issues
  e2e/cleanup/cleanup_test.go
  e2e/natsserver/natsserver_test.go
  e2e/setup/setup_test.go
  internal/controller/nats/integrationtests/controller/integration_test.go
  internal/controller/nats/integrationtests/controllersinglecr/integration_test.go
  internal/controller/nats/integrationtests/validation/integration_test.go
  testutils/integration/integration.go
  testutils/utils.go
Labels: area/eventing, lgtm

#130 Sync values from kyma and management-plane-config
  api/v1alpha1/nats_types.go
  config/samples/default.yaml
  pkg/manager/overrides_test.go
  resources/nats/values.yaml
Labels: size/M, area/eventing, lgtm

#132 add release scripts based on kyma-project/keda-manager
  .env
  .github/workflows/create-release.yaml
  .version
  Makefile
  hack/ci/Makefile
  scripts/check_image.sh
  scripts/check_release_tag.sh
  scripts/create_changelog.sh
  scripts/create_draft_release.sh
  scripts/publish_release.sh
  scripts/release.sh
  scripts/verify-status.sh
Labels: area/eventing, area/ci, size/L, lgtm

#133 disable unit tests during release
  .github/workflows/create-release.yaml
Labels: area/eventing, area/ci, lgtm, size/XS

#134 dont wait for run-unit-tests
  .github/workflows/create-release.yaml
Labels: area/eventing, area/ci, lgtm, size/XS

#135 bump nats-manager in security-scan-config
  sec-scanners-config.yaml
Labels: area/eventing, lgtm, size/XS

#136 call verify-status
  .github/workflows/create-release.yaml
Labels: area/eventing, area/ci, lgtm, size/XS

#137 bump image
  sec-scanners-config.yaml
Labels: area/eventing, lgtm, size/XS

#138 bump image before release
  .version
  scripts/check_image.sh
  sec-scanners-config.yaml
Labels: area/eventing, lgtm, size/XS

#139 fix release scripts
  .version
  Makefile
  config/manager/kustomization.yaml
  scripts/release.sh
  sec-scanners-config.yaml
Labels: area/eventing, size/S, lgtm

#140 upload nats-default-cr to release
  .version
  scripts/release.sh
  sec-scanners-config.yaml
Labels: area/eventing, lgtm, size/XS

#141 rename module in sec scanner
  sec-scanners-config.yaml
Labels: area/eventing, lgtm, size/XS

#145 Block deletion if customer stream and sap stream consumer exists
  api/v1alpha1/nats_status.go
  api/v1alpha1/nats_types.go
  internal/controller/nats/deprovisioner.go
  internal/controller/nats/deprovisioner_test.go
  internal/controller/nats/mocks/client.go
  pkg/nats/client.go
  pkg/nats/mocks/client.go
Labels: size/L, lgtm

#146 Update metadata for nats-manager 0.1.4
  .version
  sec-scanners-config.yaml
Labels: lgtm, size/XS

#148 add PriorityClass
  config/manager/kustomization.yaml
  config/manager/priority-class.yaml
  e2e/common/fixtures/fixtures.go
  e2e/setup/setup_test.go
  resources/nats/values.yaml
Labels: size/M, area/ci, lgtm

#150 Sync test CRD defaults
  config/crd/bases/operator.kyma-project.io_nats.yaml
  internal/controller/nats/integrationtests/validation/integration_test.go
Labels: size/M, lgtm

#149 Add UI for NATS module
  config/default/kustomization.yaml
  config/ui-extensions/kustomization.yaml
  config/ui-extensions/nats/details
  config/ui-extensions/nats/form
  config/ui-extensions/nats/general
  config/ui-extensions/nats/kustomization.yaml
  config/ui-extensions/nats/list
Labels: size/M, area/eventing, lgtm

#157 Bump images for nats-manager release
  .version
  sec-scanners-config.yaml
Labels: lgtm, size/XS
