Repository kyma-project/nats-manager, pull requests merged in 2023-06, with the labels that each got.

#58 Upgrade k8s version in envtest
  Makefile
  api/v1alpha1/zz_generated.deepcopy.go
  internal/controller/nats/integrationtests/validation/integration_test.go
  internal/controller/nats/mocks/controller.go
  internal/controller/nats/mocks/manager.go
  pkg/k8s/chart/mocks/renderer.go
  pkg/k8s/mocks/client.go
  pkg/manager/mocks/manager.go
Labels: size/S, lgtm

#56 Refactor deletion in integration test
  internal/controller/nats/integrationtests/controller/integration_test.go
  internal/controller/nats/mocks/controller.go
  internal/controller/nats/mocks/manager.go
  pkg/k8s/chart/mocks/renderer.go
  pkg/k8s/mocks/client.go
  pkg/manager/mocks/manager.go
  testutils/integration/integration.go
Labels: size/L, lgtm

#60 validation for spec.cluster.size
  api/v1alpha1/nats_types.go
  config/crd/bases/operator.kyma-project.io_nats.yaml
  internal/controller/nats/integrationtests/validation/integration_test.go
Labels: size/S, lgtm

#62 Prevent reconciling on more than one NATS-CR
  api/v1alpha1/nats_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  cmd/main.go
  config/manager/manager.yaml
  internal/controller/nats/controller.go
  internal/controller/nats/controller_test.go
  internal/controller/nats/integrationtests/controller/integration_test.go
  internal/controller/nats/integrationtests/controllersinglecr/integration_test.go
  internal/controller/nats/integrationtests/validation/integration_test.go
  internal/controller/nats/mocks/controller.go
  internal/controller/nats/mocks/manager.go
  internal/controller/nats/unit_test.go
  pkg/env/config.go
  pkg/env/config_test.go
  pkg/k8s/chart/mocks/renderer.go
  pkg/k8s/mocks/client.go
  pkg/manager/mocks/manager.go
  testutils/integration/integration.go
  testutils/matchers/nats/matchers.go
Labels: size/L, lgtm

#61 add defaulting to nats-cr in nats-manger
  api/v1alpha1/nats_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  cmd/main.go
  config/crd/bases/operator.kyma-project.io_nats.yaml
  config/samples/kyma-prod.yaml
  config/samples/minimal.yaml
  config/samples/nats-full-spec.yaml
  internal/controller/nats/integrationtests/controller/integration_test.go
  internal/controller/nats/integrationtests/validation/integration_test.go
  internal/controller/nats/mocks/controller.go
  internal/controller/nats/mocks/manager.go
  pkg/k8s/chart/mocks/renderer.go
  pkg/k8s/mocks/client.go
  pkg/manager/mocks/manager.go
  pkg/manager/overrides.go
  pkg/manager/overrides_test.go
  testutils/integration/integration.go
  testutils/matchers/nats/matchers.go
  testutils/options.go
  testutils/utils.go
Labels: size/XL, lgtm

#64 add validation of `memStorage` and `fileStorage`
  api/v1alpha1/nats_types.go
  config/crd/bases/operator.kyma-project.io_nats.yaml
  internal/controller/nats/integrationtests/validation/integration_test.go
  testutils/integration/integration.go
  testutils/matchers/nats/matchers.go
  testutils/utils.go
Labels: size/L, lgtm

#67 add gh action to validate the crd
  .github/workflows/validatecrd.yml
Labels: area/ci, size/S, lgtm

#63 Made log-level configurable for nats-manager
  api/v1alpha1/zz_generated.deepcopy.go
  cmd/main.go
  config/manager/manager.yaml
  pkg/env/config.go
  pkg/env/config_test.go
Labels: size/M, lgtm
