Repository kyma-project/nats-manager, pull requests merged in 2023-08, with the labels that each got.

#94 NATS Manager Documentation for User
  docs/OWNERS
  docs/README.md
  docs/assets/FlowCharts.md
  docs/user/01-manager.md
  docs/user/02-configuration.md
  docs/user/README.md
  docs/user/_sidebar.md
Labels: area/documentation, size/L, lgtm

#93 NATS Manager Documentation for Contributor
  docs/contributor/development.md
  docs/contributor/governance.md
  docs/contributor/installation.md
  docs/contributor/testing.md
  docs/contributor/troubleshooting.md
Labels: area/documentation, size/L, lgtm

#100 REUSE metadata proposal
  .reuse/dep5
  LICENSES/Apache-2.0.txt
Labels: size/M, lgtm

#103 add unit test gh action
  .github/workflows/codequality.yml
  .github/workflows/lint.yml
Labels: size/M, area/ci, lgtm

#102 makefile cleanup
  .github/workflows/codequality.yml
  Makefile
  README.md
  go.mod
  go.sum
  hack/tools.go
  internal/controller/nats/controller.go
  internal/controller/nats/mocks/controller.go
  internal/controller/nats/mocks/manager.go
  pkg/k8s/chart/mocks/renderer.go
  pkg/k8s/chart/types.go
  pkg/k8s/client.go
  pkg/k8s/mocks/client.go
  pkg/manager/mocks/manager.go
  pkg/manager/nats.go
  pkg/nats/client.go
  pkg/nats/mocks/client.go
Labels: area/ci, size/L, lgtm

#111 reuse compliance
  README.md
Labels: lgtm, size/XS

#101 add sections required by ospo
  README.md
Labels: size/S, lgtm

#98 add initial security scanner configuration
  sec-scanners-config.yaml
Labels: area/ci, size/S, lgtm

#119 Remove usage of external git actions
  .github/workflows/pull-with-lifecycle-manager.yaml
  .github/workflows/pull-without-lifecycle-manager.yml
  .github/workflows/push-with-lifecycle-manager.yaml
  .github/workflows/validatecrd.yml
  hack/ci/Makefile
Labels: size/M, area/ci, lgtm

#109 Create dependabot.yml
  .github/dependabot.yml
Labels: area/ci, size/S, lgtm

#112 k8s Events for State Changes
  api/v1alpha1/nats_types.go
  config/rbac/role.yaml
  internal/controller/nats/controller.go
  internal/controller/nats/controller_test.go
  internal/controller/nats/deprovisioner.go
  internal/controller/nats/deprovisioner_test.go
  internal/controller/nats/integrationtests/controller/integration_test.go
  internal/controller/nats/provisioner.go
  internal/controller/nats/provisioner_test.go
  internal/controller/nats/unit_test.go
  pkg/events/events.go
  testutils/integration/integration.go
  testutils/matchers/nats/matchers.go
Labels: size/L, lgtm

#121 Updated steps to deploy with lifecycle manager
  README.md
Labels: size/L, lgtm

#126 Update deps as per Kyma main
  sec-scanners-config.yaml
Labels: area/security, area/eventing, lgtm
