Repository kyma-project/nats-manager, pull requests merged in 2023-04, with the labels that each got.

#18 Added NATS manager for deploying k8s objects
  .mockery.yaml
  Makefile
  api/v1alpha1/nats_status.go
  api/v1alpha1/nats_status_test.go
  api/v1alpha1/nats_types.go
  api/v1alpha1/utils.go
  api/v1alpha1/utils_test.go
  cmd/main.go
  config/samples/all-access.yaml
  go.mod
  go.sum
  internal/controller/nats/controller.go
  internal/controller/nats_controller.go
  pkg/k8s/chart/helmrenderer_test.go
  pkg/k8s/chart/mocks/renderer.go
  pkg/k8s/client.go
  pkg/k8s/mocks/client.go
  pkg/manager/mocks/manager.go
  pkg/manager/nats.go
  pkg/manager/nats_test.go
  pkg/provisioner/nats.go
  testutils/options.go
  testutils/testutils.go
  testutils/utils.go
Labels: size/XXL, lgtm

#19 Implemented controller for NATS CR
  Makefile
  api/v1alpha1/nats_status.go
  api/v1alpha1/nats_types.go
  api/v1alpha1/utils_test.go
  cmd/main.go
  config/manager/manager.yaml
  config/rbac/role.yaml
  go.mod
  go.sum
  internal/controller/nats/controller.go
  internal/controller/nats/controller_test.go
  internal/controller/nats/deprovisioner.go
  internal/controller/nats/deprovisioner_test.go
  internal/controller/nats/provisioner.go
  internal/controller/nats/provisioner_test.go
  internal/controller/nats/status.go
  internal/controller/nats/status_test.go
  internal/controller/nats/unit_test.go
  internal/controller/nats/utils.go
  internal/controller/nats/utils_test.go
  pkg/env/config.go
  pkg/env/config_test.go
  pkg/k8s/chart/mocks/renderer.go
  pkg/k8s/client.go
  pkg/k8s/client_test.go
  pkg/k8s/mocks/client.go
  pkg/manager/mocks/manager.go
  testutils/options.go
  testutils/utils.go
Labels: size/XXL, lgtm

#29 Change nats spelling
  pkg/manager/nats.go
Labels: size/S, lgtm

#27 React to changes of the deployed resources
  go.mod
  internal/controller/nats/controller.go
  internal/controller/nats/controller_test.go
  internal/controller/nats/deprovisioner.go
  internal/controller/nats/deprovisioner_test.go
  internal/controller/nats/mocks/controller.go
  internal/controller/nats/provisioner.go
  internal/controller/nats/provisioner_test.go
  internal/controller/nats/status.go
  internal/controller/nats/status_test.go
  internal/controller/nats/unit_test.go
  pkg/file/exists_test.go
  pkg/k8s/chart/releaseinstance.go
  pkg/k8s/chart/releaseinstance_test.go
  pkg/k8s/client.go
  pkg/k8s/types.go
  pkg/manager/nats_test.go
  pkg/manager/options.go
  pkg/manager/options_test.go
Labels: size/XL, lgtm

#31 use resource.Quantities for sizes in the CRD
  api/v1alpha1/nats_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/operator.kyma-project.io_nats.yaml
  pkg/k8s/chart/mocks/renderer.go
  pkg/k8s/mocks/client.go
  pkg/manager/mocks/manager.go
Labels: size/M, lgtm

#32 Map overrides from NATS CR to helm chart
  .github/workflows/lint.yml
  api/v1alpha1/utils.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/samples/nats-full-spec.yaml
  internal/controller/nats/controller.go
  internal/controller/nats/controller_test.go
  internal/controller/nats/deprovisioner_test.go
  internal/controller/nats/provisioner_test.go
  pkg/manager/mocks/manager.go
  pkg/manager/nats.go
  pkg/manager/overrides.go
  pkg/manager/overrides_test.go
  resources/nats/templates/accounts-secret.yaml
  resources/nats/templates/configmap.yaml
  resources/nats/templates/destination-rule.yaml
  resources/nats/templates/service.yaml
  resources/nats/templates/statefulset.yaml
  resources/nats/values.yaml
  testutils/options.go
Labels: size/XL, area/ci, lgtm
