Repository kyma-project/nats-manager, pull requests merged in 2023-05, with the labels that each got.

#34 Initial setup for integration tests using envTest for NATS-manager controller
  api/v1alpha1/zz_generated.deepcopy.go
  go.mod
  go.sum
  internal/controller/nats/controller_integration_test.go
  internal/controller/nats/integration_test.go
  pkg/k8s/chart/mocks/renderer.go
  pkg/k8s/mocks/client.go
  pkg/manager/mocks/manager.go
  pkg/manager/nats.go
  pkg/manager/nats_test.go
  resources/nats/templates/service.yaml
  resources/nats/templates/statefulset.yaml
  testutils/matchers/nats/matchers.go
  testutils/options.go
  testutils/setup_helpers.go
  testutils/utils.go
Labels: size/XL, lgtm

#36 move integration test setup into testutils
  internal/controller/nats/controller_integration_test.go
  testutils/integration/integration.go
Labels: size/M, lgtm

#35 Write integration tests using envTest for NATS-manager controller
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/external/destinationrules.networking.istio.io.yaml
  go.mod
  go.sum
  internal/controller/nats/controller_integration_test.go
  resources/nats/templates/configmap.yaml
  testutils/integration/integration.go
  testutils/matchers/nats/matchers.go
  testutils/utils.go
Labels: size/XXL, lgtm

#37 Update documentation
  README.md
Labels: size/L, lgtm

#44 Setup RBAC
  config/rbac/role.yaml
  internal/controller/nats/controller.go
Labels: size/M, lgtm

#48 Updated helm chart to render same yaml for STS as in Kyma
  api/v1alpha1/zz_generated.deepcopy.go
  config/samples/kyma-prod.yaml
  config/samples/operator_v1alpha1_nats.yaml
  resources/nats/templates/_helpers.tpl
  resources/nats/templates/statefulset.yaml
  resources/nats/values.yaml
Labels: size/M, lgtm

#43 Flow charts
  docs/FlowCharts.md
Labels: area/documentation, size/M, lgtm

#57 Bump k8s pkgs
  config/crd/bases/operator.kyma-project.io_nats.yaml
  go.mod
  go.sum
  internal/controller/nats/controller.go
  internal/controller/nats/mocks/controller.go
  internal/controller/nats/mocks/manager.go
  internal/controller/nats/provisioner_test.go
  internal/controller/nats/status.go
  internal/controller/nats/status_test.go
  internal/controller/nats/unit_test.go
  pkg/k8s/chart/mocks/renderer.go
  pkg/k8s/mocks/client.go
  pkg/manager/mocks/manager.go
Labels: size/XXL, lgtm

#55 Fixed envtest setup to run multiple instances and added a validation sample test
  api/v1alpha1/nats_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/operator.kyma-project.io_nats.yaml
  internal/controller/nats/integrationtests/controller/integration_test.go
  internal/controller/nats/integrationtests/validation/integration_test.go
  testutils/integration/integration.go
Labels: size/L, lgtm
