Repository kyma-project/nats-manager, pull requests merged in 2023-11, with the labels that each got.

#211 Fix the navigation file
  docs/user/_sidebar.md
Labels: area/documentation, lgtm, size/XS

#214 Update sec-scanners-config.yaml: fix nats-manager tag
  sec-scanners-config.yaml
Labels: kind/bug, area/security, lgtm, size/XS

#200 For tests Ignore changes to the sec-scanner-config.
  .github/workflows/codequality.yml
  .github/workflows/pull-with-lifecycle-manager.yaml
  .github/workflows/pull-without-lifecycle-manager.yml
  .github/workflows/push-with-lifecycle-manager.yaml
  .github/workflows/test.yml
Labels: area/ci, lgtm, size/XS

#227 Add diagrams made in drawio
  docs/user/01-manager.md
  docs/user/README.md
  docs/user/assets/NC_watches_resources.drawio.svg
  docs/user/assets/Start_nats_manager.drawio.svg
  docs/user/assets/reacting_to_nats_cr_changes.drawio.svg
  docs/user/assets/reacting_to_resource_changes.drawio.svg
Labels: area/documentation, size/M, lgtm

#233 Add function to create a NATS CR with warning state
  testutils/options.go
Labels: lgtm, size/XS
