Repository kyma-project/nats-manager, pull requests merged in 2023-12, with the labels that each got.

#236 Use common labels for the NATS manager resources
  config/crd/bases/operator.kyma-project.io_nats.yaml
  config/default/kustomization.yaml
  config/manager/manager.yaml
  config/manager/priority-class.yaml
  config/rbac/role.yaml
  config/rbac/role_binding.yaml
  config/rbac/service_account.yaml
  internal/controller/nats/integrationtests/validation/integration_test.go
  pkg/manager/overrides_test.go
  resources/nats/templates/_helpers.tpl
  resources/nats/values.yaml
Labels: kind/bug, size/M, area/eventing, lgtm, cla: yes

#242 Bump natsio images
  resources/nats/values.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#239 Add NATS URL in the NATS CR status
  api/v1alpha1/nats_status.go
  api/v1alpha1/nats_status_test.go
  api/v1alpha1/nats_types.go
  config/crd/bases/operator.kyma-project.io_nats.yaml
  docs/user/02-configuration.md
  internal/controller/nats/deprovisioner.go
  internal/controller/nats/integrationtests/controller/integration_test.go
  internal/controller/nats/provisioner.go
  internal/controller/nats/url/url.go
  internal/controller/nats/url/url_test.go
  testutils/integration/integration.go
Labels: area/eventing, size/L, lgtm, cla: yes

#244 docs: Adjust NATS to new content guidelines
  README.md
  docs/contributor/development.md
  docs/contributor/governance.md
  docs/contributor/installation.md
  docs/contributor/testing.md
  docs/contributor/troubleshooting.md
  docs/user/01-manager.md
  docs/user/10-nats-server-system-events.md
  docs/user/README.md
  docs/user/_sidebar.md
Labels: documentation, size/L, lgtm, cla: yes

#263 Bumped Golang and k8s pkgs
  Dockerfile
  api/v1alpha1/zz_generated.deepcopy.go
  go.mod
  go.sum
  internal/controller/suite_test.go
  testutils/utils.go
Labels: size/L, lgtm, cla: yes

#259 release with semantic versioning
  .github/scripts/check-prow-build-job.sh
  .github/scripts/check_sec-scanners-config.sh
  .github/scripts/check_tag_does_not_exist.sh
  .github/scripts/check_version_format.sh
  .github/scripts/create_changelog.sh
  .github/scripts/create_draft_release.sh
  .github/scripts/publish_release.sh
  .github/scripts/render_and_upload_manifests.sh
  .github/scripts/verify_is_on_release_branch.sh
  .github/workflows/create-release.yaml
  scripts/create_changelog.sh
  scripts/release.sh
  scripts/verify-status.sh
  sec-scanners-config.yaml
Labels: area/ci, size/L, lgtm, cla: yes

#266 fix the order in which release scripts run
  .github/workflows/create-release.yaml
Labels: area/ci, lgtm, size/XS, cla: yes

#269 Bump dependencies in nats-manager
  api/v1alpha1/zz_generated.deepcopy.go
  go.mod
  go.sum
  internal/controller/nats/mocks/controller.go
  internal/controller/nats/mocks/manager.go
  pkg/k8s/chart/helmrenderer.go
  pkg/k8s/chart/mocks/renderer.go
  pkg/k8s/chart/releaseinstance.go
  pkg/k8s/mocks/client.go
  pkg/manager/mocks/manager.go
  pkg/nats/mocks/client.go
Labels: size/M, lgtm, cla: yes

#271 bump the image used in sec-scanners-config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes
