Repository kyma-project/nats-manager, pull requests merged in 2024-09, with the labels that each got.

#422 chore: upgrade golangci-lint version to v1.60.3
  .github/workflows/codequality.yml
Labels: area/ci, lgtm, size/XS, cla: yes

#423 docs: update the contributing file
  CONTRIBUTING.md
Labels: lgtm, size/XS, cla: yes

#431 chore: added github action based build jobs
  .github/workflows/pull-build-image.yaml
  .github/workflows/push-build-image.yaml
  .github/workflows/tag-build-image.yaml
  Dockerfile
Labels: area/ci, size/L, lgtm, cla: yes

#433 chore: replace prow build job waiting with github action
  .github/workflows/create-release.yaml
  .github/workflows/pull-e2e-test.yml
  .github/workflows/pull-e2e-upgrade-test.yaml
  .github/workflows/push-e2e-upgrade-test.yaml
Labels: area/ci, size/L, lgtm, cla: yes

#432 chore: image bump
  go.mod
  go.sum
Labels: size/L, lgtm, cla: yes

#434 chore: bump golang version to 1.23.1
  Dockerfile
  go.mod
Labels: lgtm, size/XS, cla: yes

#436 fix: remove prow reference
  docs/contributor/testing.md
Labels: size/S, lgtm, cla: yes
