Repository kyma-project/nats-manager, pull requests merged in 2024-12, with the labels that each got.

#465 chore: upgrade depenedencies
  go.mod
  go.sum
Labels: size/L, lgtm, cla: yes

#470 chore: bump dependencies
  go.mod
  go.sum
Labels: size/L, lgtm, cla: yes

#478 fix: retry functions
  e2e/common/retry.go
Labels: size/S, lgtm, cla: yes

#481 chore: bump dependencies and tooling
  .github/workflows/codequality.yml
  Makefile
  docs/user/02-configuration.md
  go.mod
  go.sum
  internal/controller/nats/mocks/manager.go
  internal/controller/nats/mocks/typed_controller.go
  pkg/k8s/chart/mocks/renderer.go
  pkg/k8s/mocks/client.go
  pkg/manager/mocks/manager.go
  pkg/metrics/mocks/collector.go
  pkg/nats/mocks/client.go
  pkg/nats/mocks/conn.go
  pkg/nats/mocks/jet_stream_context.go
Labels: area/ci, size/L, lgtm, cla: yes

#482 chore: cherry pick for 1.2.2
  .github/workflows/codequality.yml
  .github/workflows/create-release.yaml
  .github/workflows/lint-conventional-prs.yml
  .github/workflows/pull-build-image.yaml
  .github/workflows/pull-e2e-test.yml
  .github/workflows/pull-e2e-upgrade-test.yaml
  .github/workflows/push-build-image.yaml
  .github/workflows/push-e2e-upgrade-test.yaml
  .github/workflows/tag-build-image.yaml
  .golangci.yaml
  CONTRIBUTING.md
  Dockerfile
  Makefile
  README.md
  config/crd/bases/operator.kyma-project.io_nats.yaml
  config/rbac/role.yaml
  config/ui-extensions/nats/general
  docs/contributor/testing.md
  docs/contributor/troubleshooting.md
  docs/user/02-configuration.md
  e2e/common/retry.go
  go.mod
  go.sum
  internal/controller/nats/controller.go
  internal/controller/nats/mocks/controller.go
  internal/controller/nats/mocks/manager.go
  internal/controller/nats/mocks/natsconn.go
  internal/controller/nats/mocks/typed_controller.go
  internal/controller/nats/status.go
  internal/controller/nats/status_test.go
  pkg/k8s/chart/mocks/renderer.go
  pkg/k8s/mocks/client.go
  pkg/manager/mocks/manager.go
  pkg/metrics/mocks/collector.go
  pkg/nats/client.go
  pkg/nats/client_unit_test.go
  pkg/nats/mocks/client.go
  pkg/nats/mocks/conn.go
  pkg/nats/mocks/jet_stream_context.go
  sec-scanners-config.yaml
Labels: size/XXL, area/ci, lgtm, cla: yes

#483 chore: bump the sec-scanners-config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes
