Repository kyma-project/nats-manager, pull requests merged in 2024-04, with the labels that each got.

#355 chore: update golang version to 1.22.2
  Dockerfile
  go.mod
Labels: lgtm, size/XS, cla: yes

#357 chore: use local lint configuration
  .github/workflows/codequality.yml
  .github/workflows/test.yml
  .gitignore
  .golangci.yaml
  Makefile
  internal/controller/nats/controller.go
  internal/controller/nats/controller_test.go
  pkg/manager/nats.go
  pkg/manager/overrides_test.go
  testutils/integration/integration.go
  testutils/utils.go
Labels: area/ci, size/L, lgtm, cla: yes

#359 chore: added status information to reflect the number of AZs a cluster is spread across
  .golangci.yaml
  api/v1alpha1/nats_status.go
  api/v1alpha1/nats_status_test.go
  api/v1alpha1/nats_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  cmd/main.go
  config/crd/bases/operator.kyma-project.io_nats.yaml
  config/rbac/role.yaml
  go.mod
  internal/controller/cache/cache.go
  internal/controller/cache/cache_test.go
  internal/controller/nats/controller.go
  internal/controller/nats/deprovisioner.go
  internal/controller/nats/deprovisioner_test.go
  internal/controller/nats/integrationtests/availabilityzones/integration_test.go
  internal/controller/nats/integrationtests/validation/integration_test.go
  internal/controller/nats/mocks/controller.go
  internal/controller/nats/mocks/manager.go
  internal/controller/nats/provisioner.go
  internal/controller/nats/provisioner_test.go
  internal/controller/nats/unit_test.go
  internal/controller/nats/utils.go
  pkg/k8s/chart/mocks/renderer.go
  pkg/k8s/client.go
  pkg/k8s/client_test.go
  pkg/k8s/mocks/client.go
  pkg/manager/mocks/manager.go
  pkg/metrics/metrics.go
  pkg/metrics/mocks/collector.go
  pkg/nats/mocks/client.go
  testutils/integration/integration.go
  testutils/matchers/nats/matchers.go
  testutils/options.go
  testutils/utils.go
Labels: size/XXL, lgtm, cla: yes
