Repository kyma-project/nats-manager, pull requests merged in 2024-01, with the labels that each got.

#272 Implement caching rules
  cmd/main.go
  internal/controller/cache/cache.go
  internal/controller/cache/cache_test.go
  pkg/labels/labels.go
  pkg/labels/labels_test.go
Labels: size/L, lgtm, cla: yes

#275 bump the image tag in sec-scanner-config for rel 1.0.3
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#279 add retry logic to the build jobs validation
  .github/scripts/check-prow-build-job.sh
Labels: size/M, area/ci, lgtm, cla: yes

#284 set the right image for the release (#283)
  .github/scripts/render_and_upload_manifests.sh
  .github/workflows/create-release.yaml
Labels: area/ci, size/S, lgtm, cla: yes

#287 Install NATS Manager w/o LM
  .github/workflows/pull-e2e-test.yml
  .github/workflows/pull-e2e-upgrade-test.yaml
  .github/workflows/pull-with-lifecycle-manager.yaml
  .github/workflows/push-e2e-upgrade-test.yaml
  .github/workflows/push-with-lifecycle-manager.yaml
  hack/ci/Makefile
Labels: size/XL, area/ci, lgtm, cla: yes

#273 Upgrade NATS Server to 2.10.7 and helm chart configs
  e2e/setup/setup_test.go
  resources/nats/templates/configmap.yaml
  resources/nats/templates/statefulset.yaml
  resources/nats/values.yaml
  testutils/integration/integration.go
Labels: size/M, lgtm, cla: yes

#296 Upgrade NATS images to fix security issues
  resources/nats/values.yaml
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#299 Bumped dependencies
  config/crd/bases/operator.kyma-project.io_nats.yaml
  config/rbac/role.yaml
  go.mod
  go.sum
  internal/controller/nats/deprovisioner_test.go
  internal/controller/nats/mocks/controller.go
  internal/controller/nats/mocks/manager.go
  internal/controller/nats/provisioner_test.go
  pkg/k8s/chart/mocks/renderer.go
  pkg/k8s/mocks/client.go
  pkg/manager/mocks/manager.go
  pkg/nats/mocks/client.go
Labels: size/L, lgtm, cla: yes

#300 Fix a link
  docs/contributor/testing.md
Labels: lgtm, size/XS, cla: yes

#302 Update README.md
  CODE_OF_CONDUCT.md
  README.md
Labels: size/M, lgtm, cla: yes

#301 Changed image tag to main in sec-scanners-config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#305 Remove module-template
  .gitignore
  Makefile
  hack/ci/Makefile
  hack/get_module_template_from_build_job.sh
  module-config-template.yaml
Labels: size/L, lgtm, cla: yes
