Repository kyma-project/nats-manager, pull requests merged in 2024-02, with the labels that each got.

#307 Bump image in sec scanner config - release 1.1.0
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#308 Bump rc-tag to 1.1.0 in sec-scanners config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#309 Bump rc tag to 1.1.0 in sec-scanners config
  sec-scanners-config.yaml
Labels: lgtm, size/XS, cla: yes

#311 Bump mockery image to 2.40.3
  go.mod
  go.sum
  internal/controller/nats/mocks/controller.go
  internal/controller/nats/mocks/manager.go
  pkg/k8s/chart/mocks/renderer.go
  pkg/k8s/mocks/client.go
  pkg/manager/mocks/manager.go
  pkg/nats/mocks/client.go
Labels: size/M, lgtm, cla: yes

#315 feat: add rules for PRs
  .github/dependabot.yml
  .github/workflows/lint-conventional-prs.yml
Labels: size/M, area/ci, lgtm, cla: yes

#320 chore: update regex link in action
  .github/workflows/lint-conventional-prs.yml
Labels: area/ci, lgtm, size/XS, cla: yes

#333 Bump Golang version to 1.22.0
  .github/workflows/pull-e2e-test.yml
  .github/workflows/pull-e2e-upgrade-test.yaml
  .github/workflows/push-e2e-upgrade-test.yaml
  Makefile
  go.mod
Labels: size/M, area/ci, lgtm, cla: yes

#332 chore: change dependabot config to weekly schedule
  .github/dependabot.yml
Labels: area/ci, size/S, lgtm, cla: yes

#335 Chore: Simplify retry functions
  e2e/common/retry.go
Labels: size/M, lgtm, cla: yes

#319 fix: nats-server runs as root
  resources/nats/templates/statefulset.yaml
  resources/nats/values.yaml
Labels: area/ci, size/S, lgtm, cla: yes

#338 fix: schedule of dependabot
  .github/dependabot.yml
Labels: area/ci, lgtm, size/XS, cla: yes

#342 chore: bumped controller-runtime and fixed tests
  go.mod
  go.sum
  pkg/k8s/client_test.go
Labels: size/M, lgtm, cla: yes

#341 chore: Linter configuration: gofumpt, goerr113, godox, goconst
  .github/workflows/codequality.yml
  .gitignore
  .golangci.yaml
  api/v1alpha1/nats_status.go
  internal/controller/nats/deprovisioner.go
  internal/controller/nats/deprovisioner_test.go
  internal/controller/nats/integrationtests/controller/integration_test.go
  internal/controller/nats/provisioner.go
  internal/controller/nats/provisioner_test.go
  internal/controller/nats/status.go
  internal/controller/nats/status_test.go
  pkg/events/events.go
  pkg/k8s/chart/helmrenderer.go
  pkg/k8s/chart/releaseinstance.go
  pkg/k8s/client.go
  pkg/manager/nats.go
  pkg/manager/nats_test.go
  pkg/manager/options.go
  pkg/manager/overrides.go
  pkg/nats/client_unit_test.go
  testutils/integration/integration.go
  testutils/options.go
Labels: area/ci, size/L, lgtm, kind/cleanup, cla: yes
